# Timeout for getting IP addresses
INGRESS_IP_TIMEOUT_SECONDS: float = 60.0
INGRESS_TERMINATION_TIMEOUT: float = 20.0

# Timeout for pod uptime
POD_UPTIME_TIMEOUT: float = 20.0
POD_IP_UPTIME_TIMEOUT: float = 20.0
POD_TERMINATION_TIMEOUT: float = 20.0

SERVICE_IP_UPTIME_TIMEOUT: float = 20.0
SERVICE_TERMINATION_TIMEOUT: float = 20.0
