FROM python:3.11-slim

# Create the directory
RUN mkdir app
COPY . app/
WORKDIR app

# install dependencies
RUN apt-get update && apt-get install -y build-essential
RUN pip install -r requirements.txt

# install container maker spec
RUN pip install container-maker-spec/

# run code
CMD ["tail", "-f", "/dev/null"]
