---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-maker-debug
  namespace: browseterm  # Added namespace
  labels:
    app: container-maker-debug
spec:
  replicas: 2
  selector:
    matchLabels:
      app: container-maker-debug
  template:
    metadata:
      labels:
        app: container-maker-debug
    spec:
      containers:
      - name: container-maker-debug
        image: zim95/container-maker-debug:latest  # Your gRPC API Docker image
        ports:
        - containerPort: 50051  # gRPC default port
        env:
        - name: SERVER_KEY
          valueFrom:
            secretKeyRef:
              name: grpc-certs
              key: server.key
        - name: SERVER_CRT
          valueFrom:
            secretKeyRef:
              name: grpc-certs
              key: server.crt
        - name: CA_CRT
          valueFrom:
            secretKeyRef:
              name: grpc-certs
              key: ca.crt
      volumes: []  # No volumes needed since we're using environment variables
---
apiVersion: v1
kind: Service
metadata:
  name: container-maker-debug-service
  namespace: browseterm  # Added namespace
  labels:
    app: container-maker-debug
spec:
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  selector:
    app: container-maker-debug
  type: ClusterIP  # Use LoadBalancer for external access if needed
